// Converts every referenced JPG in public/ into responsive AVIF + WebP variants using Sharp.
//
// Runs before webpack (via the prebuild/prestart/prewatch npm hooks). It scans src/
// for JPG basenames, so adding a new image requires no config change — just reference
// it from an .ejs (via the picture() helper) or .scss (background url) and rebuild.
//
// Output: dist/public/<name>-<width>.{avif,webp} (responsive variants),
// dist/public/<name>.{avif,webp} (full size, used by the hero CSS image-set), and a
// manifest at image-manifest.json that the picture() helper reads to build the
// <picture> srcsets. Unchanged images are reused from the previous run.

const fs = require('fs');
const os = require('os');
const path = require('path');
const sharp = require('sharp');

const ROOT = path.resolve(__dirname, '..');
const SRC_DIR = path.join(ROOT, 'src');
const PUBLIC_DIR = path.join(ROOT, 'public');
const OUT_DIR = path.join(ROOT, 'dist', 'public');
const MANIFEST_PATH = path.join(ROOT, 'image-manifest.json');

const WIDTHS = [480, 768, 1024, 1440, 1920];

// Encoder settings per output format, in the order browsers should prefer them. AVIF
// at q50 matches WebP q80 visually at roughly half the bytes; WebP stays as the
// fallback for the few browsers without AVIF. `effort` only trades encode time for
// size, and the cache below keeps that cost to the first build.
const FORMATS = {
    avif: { quality: 50, effort: 4 },
    webp: { quality: 80, effort: 6, smartSubsample: true },
};

// Anything that changes the generated bytes. A manifest entry built with different
// settings is regenerated rather than reused.
const SETTINGS_KEY = JSON.stringify({ WIDTHS, FORMATS });

const TEXT_EXTENSIONS = /\.(ejs|js|ts|scss|css|html)$/;
const JPG_REF_REGEX = /[\w.-]+\.jpe?g/g;

// Collect every JPG basename mentioned anywhere in src/. This catches both
// picture('portrait.jpg') in EJS and url(".../eisbaden.jpg") in SCSS, and naturally
// excludes images that aren't referenced at all.
function findReferencedJpgs(dir, found = new Set()) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            findReferencedJpgs(full, found);
        } else if (TEXT_EXTENSIONS.test(entry.name)) {
            const content = fs.readFileSync(full, 'utf8');
            let m;
            while ((m = JPG_REF_REGEX.exec(content)) !== null) found.add(path.basename(m[0]));
        }
    }
    return found;
}

function loadPreviousManifest() {
    try {
        return JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf8'));
    } catch {
        return {};
    }
}

// Every dist-relative file a manifest entry points at.
function outputsOf(entry) {
    return (entry.variants || [])
        .flatMap((v) => Object.keys(FORMATS).map((f) => v[f]))
        .filter(Boolean);
}

// Encoding AVIF takes seconds per file, so an image is only re-encoded when its source,
// the settings, or one of its outputs changed since the previous run.
function isReusable(entry, stat) {
    return (
        entry &&
        entry.settings === SETTINGS_KEY &&
        entry.source &&
        entry.source.size === stat.size &&
        entry.source.mtimeMs === stat.mtimeMs &&
        outputsOf(entry).every((rel) => fs.existsSync(path.join(ROOT, 'dist', rel)))
    );
}

// Runs async tasks with at most `limit` in flight. The AVIF encoder is effectively
// single-threaded per file, so the speed-up comes from encoding files side by side.
async function runPool(tasks, limit) {
    const queue = [...tasks];
    const worker = async () => {
        while (queue.length) await queue.shift()();
    };
    await Promise.all(Array.from({ length: Math.min(limit, queue.length) }, worker));
}

// Plans the encodes for one image into every width × format. Returns its manifest
// variants (filled in as the tasks run) and the tasks themselves, so all images can
// share one pool. Downscaled variants for srcset (only widths smaller than the source)
// come first, then the full size — used by the hero CSS image-set() and doubling as
// the largest srcset entry, so there is no redundant `-<intrinsic width>` file.
function planEncodes(input, stem, width) {
    const targets = [
        ...WIDTHS.filter((w) => w < width).map((w) => [w, `${stem}-${w}`]),
        [width, stem],
    ];
    const variants = targets.map(([w]) => ({ width: w }));
    const tasks = targets.flatMap(([w, name], i) =>
        Object.entries(FORMATS).map(([format, options]) => async () => {
            const file = `${name}.${format}`;
            let pipeline = sharp(input);
            if (w < width) pipeline = pipeline.resize(w, null, { withoutEnlargement: true });
            await pipeline[format](options).toFile(path.join(OUT_DIR, file));
            variants[i][format] = `public/${file}`;
        }),
    );
    return { variants, tasks };
}

async function generate() {
    const referenced = findReferencedJpgs(SRC_DIR);
    // The Open Graph image is a fixed 1200x630 social asset produced by
    // scripts/generate-og-image.js and referenced by absolute URL. Crawlers fetch
    // exactly that file, so responsive variants of it would never be used.
    referenced.delete('og-image.jpg');
    fs.mkdirSync(OUT_DIR, { recursive: true });

    const previous = loadPreviousManifest();
    const manifest = {};

    const tasks = [];
    for (const basename of [...referenced].sort()) {
        const input = path.join(PUBLIC_DIR, basename);
        if (!fs.existsSync(input)) {
            console.warn(`[images] referenced but missing in public/: ${basename}`);
            continue;
        }

        const stat = fs.statSync(input);
        if (isReusable(previous[basename], stat)) {
            manifest[basename] = previous[basename];
            continue;
        }

        const stem = basename.replace(/\.jpe?g$/i, '');
        const { width, height } = await sharp(input).metadata();
        const plan = planEncodes(input, stem, width);
        tasks.push(...plan.tasks);

        manifest[basename] = {
            width,
            height,
            variants: plan.variants,
            source: { size: stat.size, mtimeMs: stat.mtimeMs },
            settings: SETTINGS_KEY,
        };
        console.log(
            `[images] ${basename} → ${plan.variants.length} size(s) × ${Object.keys(FORMATS).join(' + ')}`,
        );
    }
    await runPool(tasks, os.availableParallelism());

    // dist/ is never wiped by webpack, so outputs from deleted/renamed images (or from
    // formats and widths no longer generated) would otherwise linger.
    const current = new Set(Object.values(manifest).flatMap(outputsOf));
    for (const entry of Object.values(previous)) {
        const stale = [
            entry.webp,
            ...(entry.variants || []).flatMap((v) => [v.src, ...Object.values(v)]),
        ];
        for (const rel of stale) {
            if (typeof rel !== 'string' || current.has(rel)) continue;
            const abs = path.join(ROOT, 'dist', rel);
            if (fs.existsSync(abs)) fs.rmSync(abs);
        }
    }

    fs.writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2) + '\n');
    console.log(
        `[images] wrote ${path.relative(ROOT, MANIFEST_PATH)} (${Object.keys(manifest).length} image(s))`,
    );
}

generate().catch((err) => {
    console.error('[images] generation failed:', err);
    process.exit(1);
});
